In [1]:
import numpy as np
list_ = [1,2,3,4,5]
array_list = np.array(object = list_)

In [2]:
array_list

array([1, 2, 3, 4, 5])

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Yes, both the data type of variables list_ and array_list is different. data type of list_ and array_list is list and numpy.ndarray respectively

In [11]:
type(list_)

list

In [10]:
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [13]:
for i in list_:
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [16]:
array_list.dtype

dtype('int64')

Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [18]:
array_list=np.array(object=list_,dtype=int)

In [19]:
type(list_[0])

int

In [20]:
array_list.dtype

dtype('int64')

Datatype of both is same

Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [21]:
num_list=[[1,2,3],[4,5,6]]

In [22]:
num_array=np.array(object=num_list)

In [23]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [24]:
#shape
num_array.shape

(2, 3)

In [25]:
#size
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [36]:
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
